---
title: "678-final-project"
author: "Shengbo Wang"
date: "2022-11-29"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = F,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(tidyr)
library(ggplot2)
library(tidyverse)
library(dplyr)
```
#Abstract

The football is one of the most popular sports in United State, The National Football League is a professional American football league that consists of 32 teams

#Introduction

Russell Wilson from team Seahawks have the highest year salaries at 35 million. 

First I combine the data from https://www.kaggle.com/datasets/toddsteussie/nfl-play-statistics-dataset-2004-to-present?select=rusher.csv.

```{r}
players <- read_csv("players.csv") %>% select(playerId,nameFull,nflId)
salaries <- read_csv("football_salaries.csv") %>% select(position,nameFull=player,team,salaries=avg_year)
data1 <- inner_join(players,salaries)

rusher <- read_csv("rusher.csv") %>%
  group_by(playerId) %>%
  summarise(rushYards=sum(rushYards)) %>% 
  select(playerId,rushYards)
data2 <- right_join(data1,rusher)

receiver <- read_csv("receiver.csv") %>% 
  select(playerId,recYards,recYac,rec1down) %>% 
  group_by(playerId) %>% 
  summarise(recYards=sum(recYards),
            recYac=sum(recYac),
            rec1down=sum(rec1down))
data3 <- right_join(data2 ,receiver)

passer <- read_csv("passer.csv") %>% 
  select(playerId,passAtt) %>% 
  group_by(playerId) %>% 
  summarise(passAtt=sum(passAtt))
data4 <- right_join(data3,passer)

fumbles <- read_csv("fumbles.csv") %>% 
  select(playerId,fumTurnover) %>% 
  group_by(playerId) %>% 
  summarise(fumTurnover=sum(fumTurnover))
data5 <- right_join(data4,fumbles)

data <- data.frame(data5)
```

```{r}
ggplot(data =data) + 
  aes(x = log(recYards + 1), y = log(salaries)) + 
  geom_point(aes(color = factor(team)), size = .6) + 
  geom_smooth(aes(color = factor(team)), method = "lm", se = FALSE, formula = 'y ~ x')
```

```{r}
ggplot(data = data) + 
  aes(x = log(recYards + 1), y = log(salaries)) + 
  geom_point(aes(color = factor(position)), size = .6) + 
  geom_smooth(aes(color = factor(position)), method = "lm", se = FALSE, formula = 'y ~ x')
```
